version: '3.7'
services:
  db:
    image: mongo:latest

  shared_db:
    image: mongo:latest

  db_import:
    image: mongo:latest
    volumes:
      - ./doc:/doc
    depends_on:
      - db
      - shared_db
    command: >
      bash -c "mongoimport --host=db --port=27017 --db=artion --collection=observed --file=doc/db/observed.json 
      && mongoimport --host=db --port=27017 --db=artion --collection=status --file=doc/db/status.json
      && mongoimport --host=shared_db --port=27017 --db=artionshared --collection=colcats --file=doc/db/colcats.json 
      && mongoimport --host=shared_db --port=27017 --db=artionshared --collection=collections --file=doc/db/collections.json"

  gton_shop_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7373:7373
    depends_on:
      - 'db'
      - 'shared_db'
    command: ['/app/build/artionapi', '-cfg', '/app/config.json']
