version: '3.7'
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./docs/db:/db
    command:
      [
        'mongoimport --db=artion --collection=observed --file=db/observed.json',
        'mongoimport --db=artion --collection=status --file=db/status.json',
      ]

  gton-shop-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gton_shop_api
    ports:
      - 7373:7373
    depends_on:
      - 'db'
    command: '/app/build/artionapi -cfg /app/config.json'
